version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_NAME=microservice_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Monono123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: microservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Monono123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: